services:
  - type: web
    name: pwa-let-backend
    env: node
    plan: free
    root: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5001
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        value: ballast.proxy.rIwy.net
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        value: xoFhuNQUDkQtdVQbFueAArOVpaAAYVNb
      - key: DB_NAME
        value: pwa_let_db
      - key: DB_PORT
        value: 3306
      - key: CORS_ORIGIN
        value: https://letopwa.netlify.app
      - key: JWT_SECRET
        value: your_jwt_secret_key_here_change_in_production
      - key: UPLOAD_DIR
        value: ./uploads
      - key: MAX_FILE_SIZE
        value: 10485760
