services:
  - type: web
    name: pwa-let-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        fromBuild: true
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        value: ballast.proxy.rlwy.net
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: pwa_let_db
      - key: DB_PORT
        value: 34315
      - key: CORS_ORIGIN
        value: https://pwa-let-frontend.onrender.com,http://localhost:3000,http://127.0.0.1:3000
      - key: JWT_SECRET
        sync: false
      - key: UPLOAD_DIR
        value: ./uploads
      - key: MAX_FILE_SIZE
        value: 10485760
      - key: NODE_OPTIONS
        value: "--max-old-space-size=512"
